auth-server: http://sso-login:8082/uaa
server:
  port: 8084
  servlet:
    context-path: /client2
security:
  oauth2:
    client:
      client-id: merryyou2
      client-secret: merryyousecrect2
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
      registered-redirect-uri: http://sso-tmall:8084/client1
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key